"""models

Revision ID: 26a855340de2
Revises: 
Create Date: 2024-01-04 10:07:19.411203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a855340de2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Firstname', sa.String(), nullable=True),
    sa.Column('Lastname', sa.String(), nullable=True),
    sa.Column('Accountno', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Accountno')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Accountbalance', sa.String(), nullable=True),
    sa.Column('Chequeno', sa.String(), nullable=True),
    sa.Column('Accountno', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Accountno'], ['users.Accountno'], name=op.f('fk_transaction_Accountno_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transaction_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('users')
    # ### end Alembic commands ###
