"""tables

Revision ID: 9565e3aa05c6
Revises: 26a855340de2
Create Date: 2024-01-04 19:11:39.326376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9565e3aa05c6'
down_revision = '26a855340de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accountbalance', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('accountbalance')

    op.create_table('transaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Accountbalance', sa.VARCHAR(), nullable=True),
    sa.Column('Chequeno', sa.VARCHAR(), nullable=True),
    sa.Column('Accountno', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['Accountno'], ['users.Accountno'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_transaction_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
